site_name: Deep Plant Phenomics

pages:
    - Home: index.md
    - Documentation:
      - DPPmodel API:
        - Loaders: Loaders.md
        - Neural Network Layers: Neural-Network-Layers.md
        - Model Options: Model-Options.md
        - Data Fusion Options: Data-Fusion-Options.md
        - Semantic Segmentation: Semantic-Segmentation.md
      - Tools: Tools.md
      - Hyperparameter  Optimization: Hyperparameter-Optimization.md
      - Tutorials:
        - Tutorial - Training the Leaf Counter: Tutorial-Training-The-Leaf-Counter.md
        - Tutorial - Deploying your Trained Model: Tutorial-Deployment.md
        - Tutorial - Training an Object Detector: Tutorial-Training-An-Object-Detector.md

theme: readthedocs
